import time
import sys

print("  -_-\x1B[3mCalculator\x1B[0m-_-")
print("-_-\x1B[3mMade by gu10b\x1B[0m-_-")
print("")
print("More projects in https://t.ly/gu10bgithub")
time.sleep(2)
print("")
type = input("Type of math? ")
if type == ("+"):
    time.sleep(1.5)
    print("")
    number_1 = int(input('Enter your first number: '))
    number_2 = int(input('Enter your second number: '))
    time.sleep(1.25)
    print("")
    print("Calculating...")
    time.sleep(2.5)
    print("Your number is")
    print(number_1 + number_2)
    sys.exit()
if type == ("*"):
    time.sleep(1.5)
    print("")
    number_1 = int(input('Enter your first number: '))
    number_2 = int(input('Enter your second number: '))
    time.sleep(1.25)
    print("")
    print("Calculating...")
    time.sleep(2.5)
    print("Your number is")
    print(number_1 * number_2)
    sys.exit()
if type == ("/"):
    time.sleep(1.5)
    print("")
    number_1 = int(input('Enter your first number: '))
    number_2 = int(input('Enter your second number: '))
    time.sleep(1.25)
    print("")
    print("Calculating...")
    time.sleep(2.5)
    print("Your number is")
    print(number_1 / number_2)
    sys.exit()
